[package]
name = "expose"
version = "0.0.1"
edition = "2018"
license = "Apache-2.0 License"
authors = ["lukasjoc <jochamlu@gmail.com>"]
readme = "readme"
description = "Listen for File Changes"
repository = "https://github.com/lukasjoc/expose"

[build-dependencies]
clap = "2"

[[bin]]
name = "expose"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
notify = "4"
clap = { version = "2", default-features = false }
